# Generated by Django 5.2.12 on 2026-05-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='patients',
            table='patient',
        ),
    ]
