# Generated by Django 5.2.12 on 2026-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='doctors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='doctors',
            table='doctor',
        ),
    ]
