# Generated by Django 5.2.12 on 2026-05-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='picture',
            field=models.ImageField(default='patient/user.png', upload_to='patient/'),
        ),
    ]
