# Generated by Django 5.2.12 on 2026-05-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patients_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='file',
            field=models.FileField(default='', upload_to='file/'),
        ),
    ]
