# Generated by Django 5.2.12 on 2026-05-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patients_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='file/'),
        ),
    ]
